# See default settings https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - '*.gemspec'
    - 'Gemfile'
    - 'Guardfile'
    - 'bin/*'
    - 'Rakefile'
    - 'Steepfile'
    - 'example/**/*'
  NewCops: enable

Metrics/AbcSize:
  Max: 22

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false
