# See default settings https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - '*.gemspec'
    - 'Gemfile'
    - 'Guardfile'
    - 'bin/*'
    - 'Rakefile'
    - 'example/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false
