name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0.x', '2.7.x', '2.6.x', '2.5.x']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
